import { Roboto_Condensed } from "next/font/google";
import "./globals.css";
import QueryProviders from "./../utils/QueryProviders";

const roboto = Roboto_Condensed({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${roboto.className} `} suppressHydrationWarning={true}>
        <QueryProviders>{children}</QueryProviders>
      </body>
    </html>
  );
}
